/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프로젝트 목록 */
        get: operations["listProjects"];
        put?: never;
        /** 프로젝트 생성 */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        /** 프로젝트 상세와 현재 단계 */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /**
         * 프로젝트 삭제
         * @description 원본 자료, 분석 결과, 산출물, 모든 Revision을 함께 지운다. 유예 기간은 없다.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** 프로젝트명과 목적 수정 */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{projectId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 서명 업로드 URL 발급
         * @description 파일은 API 서버를 거치지 않고 객체 저장소로 직접 올린다 (PERF-006).
         */
        post: operations["createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        /** 올린 자료와 처리 상태 */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/sources/text": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 직접 입력한 설명 등록 */
        post: operations["createTextSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                sourceId: components["parameters"]["sourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 자료 하나 삭제 */
        delete: operations["deleteSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/sources/{sourceId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                sourceId: components["parameters"]["sourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 파일 처리 재시도
         * @description error.retryable이 true인 자료만 받는다.
         */
        post: operations["retrySource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/evidence/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        /** 확인된 사실, 부족 정보, 상충 조회 */
        get: operations["getEvidenceSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/evidence/{evidenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                evidenceId: string;
            };
            cookie?: never;
        };
        /** 원문 위치와 발췌 */
        get: operations["getEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/evidence/conflicts/{conflictId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                conflictId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 상충하는 값 중 하나 선택
         * @description 고르지 않고 넘어갈 수 있다. 그때는 확정 수치로 쓰지 않는다.
         */
        post: operations["resolveConflict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/generations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 생성 시작 */
        post: operations["startGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["jobId"];
            };
            cookie?: never;
        };
        /**
         * 작업 상태
         * @description 진행률은 백엔드가 완료한 단계만 반영한다 (PRD §5.3).
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["jobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 작업 취소 */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/decks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        /** Revision 목록 */
        get: operations["listDecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/decks/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        /** 결과 조회 */
        get: operations["getDeck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/decks/{revisionId}/previews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        /**
         * 슬라이드 이미지 URL
         * @description 브라우저에서 PPTX를 직접 렌더링하지 않는다 (PRD §10.8).
         *     백엔드가 만든 검수용 이미지를 쓴다. 썸네일 320px, 큰 이미지 1600px.
         */
        get: operations["getDeckPreviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifactId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifactId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 다운로드 URL 재발급
         * @description 만료된 서명 URL을 대신할 새 URL을 받는다 (FE-111).
         */
        post: operations["createDownloadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Page: {
            has_more: boolean;
            next_cursor?: string | null;
        };
        /**
         * @description code는 검토서 §3.3의 카탈로그를 따른다.
         *     모르는 code를 받아도 앱이 멈추지 않고 "확인 필요"로 표시한다 (PRD §17.3).
         */
        Error: {
            code: components["schemas"]["ErrorCode"];
            /** @description 서버 원문. 화면에는 프론트의 문구 표를 쓴다 */
            message: string;
            retryable: boolean;
            request_id: string;
            /** @description 422일 때 입력 칸 이름 */
            field?: string | null;
            /** @description 429일 때 */
            retry_after_seconds?: number | null;
        };
        /** @enum {string} */
        ErrorCode: "FILE_TOO_LARGE" | "FILE_TYPE_UNSUPPORTED" | "FILE_ENCRYPTED" | "FILE_CORRUPTED" | "SCAN_FAILED" | "PARSE_FAILED" | "OCR_UNAVAILABLE" | "QUOTA_EXCEEDED" | "INSUFFICIENT_EVIDENCE" | "GENERATION_TIMEOUT" | "AI_PROVIDER_ERROR" | "VALIDATION_FAILED" | "RATE_LIMITED";
        /**
         * @description 서버 상태 9종. 사용자에게는 5종으로 압축해 보여준다 (검토서 §5)
         * @enum {string}
         */
        ProjectStatus: "created" | "uploading" | "parsing" | "extracting" | "analyzing" | "planning" | "generating" | "validating" | "repairing" | "completed" | "failed" | "deleting";
        ProjectCreate: {
            company_name: string;
            industry?: string | null;
            purpose: string;
            /** Format: date */
            period_start?: string | null;
            /** Format: date */
            period_end?: string | null;
            audiences?: string[];
        };
        ProjectSummary: {
            id: string;
            company_name: string;
            purpose: string;
            status: components["schemas"]["ProjectStatus"];
            /** Format: date-time */
            updated_at: string;
            source_count: number;
            latest_revision?: components["schemas"]["DeckRevisionSummary"];
            last_error?: components["schemas"]["Error"];
        };
        Project: components["schemas"]["ProjectSummary"] & {
            industry?: string | null;
            /** Format: date */
            period_start?: string | null;
            /** Format: date */
            period_end?: string | null;
            audiences?: string[];
            /** Format: date-time */
            created_at: string;
            /**
             * @description 직접 URL로 들어와도 올바른 화면으로 보내는 데 쓴다 (PRD §7)
             * @enum {string}
             */
            current_step: "basics" | "sources" | "review" | "generate" | "job" | "deck";
            active_job_id?: string | null;
        };
        /** @description 값은 검토서 §3.1에서 확정했다 */
        Quota: {
            file_count: number;
            /** @example 20 */
            file_limit: number;
            used_bytes: number;
            /** @example 209715200 */
            byte_limit: number;
        };
        /** @enum {string} */
        SourceStatus: "pending" | "uploading" | "scanning" | "parsing" | "ocr_queued" | "ready" | "failed";
        SourceAsset: {
            id: string;
            /** @enum {string} */
            kind: "file" | "text";
            filename?: string | null;
            size_bytes?: number | null;
            content_type?: string | null;
            status: components["schemas"]["SourceStatus"];
            progress?: number | null;
            fact_count?: number | null;
            page_count?: number | null;
            /** @description kind=text일 때 */
            char_count?: number | null;
            /** @description 중복 감지 (FE-035) */
            duplicate_of?: string | null;
            error?: components["schemas"]["Error"];
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description 방주 색단의 등급. docs/DESIGN.md §2
         * @enum {string}
         */
        EvidenceGrade: "fact" | "interpretation" | "estimate";
        /** @enum {string} */
        Confidence: "high" | "medium" | "low";
        Evidence: {
            id: string;
            grade: components["schemas"]["EvidenceGrade"];
            /** @description 추출 텍스트. 인용으로만 렌더링한다 (검토서 SEC-001) */
            statement: string;
            /** @description 해석·추정일 때 근거 설명 */
            note?: string | null;
            confidence?: components["schemas"]["Confidence"];
            sources: components["schemas"]["EvidenceRef"][];
        };
        EvidenceRef: {
            source_id: string;
            /** @description 본문 상첨자 번호 */
            footnote_number: number;
            filename?: string | null;
            /** @description 8페이지, 매출 시트 B12 같은 위치 */
            locator?: string | null;
            /** @description 제어문자를 제거한 발췌 (SEC-004) */
            excerpt?: string | null;
            /** Format: date */
            checked_at?: string | null;
        };
        EvidenceGap: {
            id: string;
            /** @example 해외 상시 유통 */
            topic: string;
            /** @description 부족한 정보명과 결과에 생기는 제한 */
            message: string;
            suggested_action?: string | null;
            affects_slides?: number[];
        };
        EvidenceConflict: {
            id: string;
            /** @example 2024년 매출 */
            metric: string;
            candidates: {
                id: string;
                value_text: string;
                source: components["schemas"]["EvidenceRef"];
            }[];
            resolved: boolean;
            chosen_candidate_id?: string | null;
        };
        EvidenceSummary: {
            company: {
                name?: string;
                industry?: string | null;
                founded?: string | null;
                /** Format: date */
                period_start?: string | null;
                /** Format: date */
                period_end?: string | null;
            };
            counts: {
                sources_total: number;
                sources_ready: number;
                facts: number;
                needs_review: number;
            };
            items: components["schemas"]["Evidence"][];
            gaps: components["schemas"]["EvidenceGap"][];
            conflicts: components["schemas"]["EvidenceConflict"][];
            sources: components["schemas"]["EvidenceRef"][];
        };
        GenerationRequest: {
            /** @default 12 */
            slide_count: number;
            /** @default ko */
            language: string;
            /** @description MVP는 pptx만. pdf는 Phase 2 */
            outputs: "pptx"[];
            /** @default default-ir */
            template: string;
        };
        /**
         * @description 사용자 문구는 PRD §10.7 표를 따른다
         * @enum {string}
         */
        JobStage: "scanning" | "parsing" | "extracting" | "analyzing" | "planning" | "generating" | "validating" | "repairing" | "completed" | "failed" | "cancelled";
        Job: {
            id: string;
            project_id: string;
            stage: components["schemas"]["JobStage"];
            /** @description 완료한 단계만 반영한다 */
            progress: number;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at?: string | null;
            eta_seconds?: number | null;
            completed_stages: {
                stage: components["schemas"]["JobStage"];
                /** Format: date-time */
                finished_at: string;
                detail?: string | null;
            }[];
            slides_done?: number | null;
            slides_total?: number | null;
            warnings?: components["schemas"]["JobWarning"][];
            error?: components["schemas"]["Error"];
            /** @description 완료 시 결과 Revision */
            revision_id?: string | null;
        };
        /** @description 경고는 오류와 다르게 표시한다 (PRD §5.4) */
        JobWarning: {
            code: string;
            message: string;
            affects_slides?: number[];
        };
        DeckRevisionSummary: {
            id: string;
            revision_number: number;
            slide_count: number;
            /** Format: date-time */
            created_at: string;
            artifacts?: components["schemas"]["Artifact"][];
        };
        DeckRevision: components["schemas"]["DeckRevisionSummary"] & {
            slides: components["schemas"]["Slide"][];
            totals: {
                facts_used?: number;
                gaps?: number;
                estimates?: number;
            };
        };
        Slide: {
            number: number;
            title: string;
            /** @description 한 장이 전달하는 하나의 결론 */
            conclusion: string;
            evidence_refs: components["schemas"]["EvidenceRef"][];
            grades?: components["schemas"]["EvidenceGrade"][];
            gaps?: components["schemas"]["EvidenceGap"][];
            warnings?: components["schemas"]["JobWarning"][];
        };
        SlidePreview: {
            number: number;
            /**
             * Format: uri
             * @description 320px 폭
             */
            thumbnail_url: string;
            /**
             * Format: uri
             * @description 1600px 폭
             */
            large_url: string;
            width: number;
            height: number;
            /** @description 번호와 제목 (A11Y-008) */
            alt?: string;
        };
        Artifact: {
            id: string;
            /** @enum {string} */
            type: "pptx";
            filename: string;
            size_bytes: number;
            checksum?: string | null;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: uri
             * @description 만료되면 재발급받는다
             */
            download_url?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
        };
    };
    responses: {
        /** @description 인증 필요 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 없거나 접근할 수 없다 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 파일이 너무 크다 */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 서버 검증 실패. field로 입력 칸과 연결한다 */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        projectId: string;
        sourceId: string;
        jobId: string;
        revisionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: {
                /** @description 회사명 검색 */
                q?: string;
                status?: components["schemas"]["ProjectStatus"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 최근 수정순 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProjectSummary"][];
                        page: components["schemas"]["Page"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description 생성됨 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 현재 단계 복원에 쓴다 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 시작. status가 deleting으로 바뀐다 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    company_name?: string;
                    purpose?: string;
                };
            };
        };
        responses: {
            /** @description 수정됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 한글 파일명을 그대로 받는다 */
                    filename: string;
                    /** @description 50MB 상한 */
                    size_bytes: number;
                    content_type: string;
                };
            };
        };
        responses: {
            /** @description 발급됨 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        source_asset_id: string;
                        /** Format: uri */
                        upload_url: string;
                        /** Format: date-time */
                        expires_at: string;
                    };
                };
            };
            413: components["responses"]["TooLarge"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 업로드 순서와 무관하게 안정된 순서를 유지한다 (FE-041) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SourceAsset"][];
                        quota: components["schemas"]["Quota"];
                    };
                };
            };
        };
    };
    createTextSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        responses: {
            /** @description 등록됨. 이 내용도 출처로 남는다 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAsset"];
                };
            };
        };
    };
    deleteSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                sourceId: components["parameters"]["sourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    retrySource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                sourceId: components["parameters"]["sourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 재시도 시작 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAsset"];
                };
            };
            /** @description 재시도할 수 없는 실패 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEvidenceSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 자료 검토 화면의 주 데이터 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSummary"];
                };
            };
        };
    };
    getEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                evidenceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 출처 드로어에 쓴다 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    resolveConflict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                conflictId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    chosen_candidate_id: string;
                };
            };
        };
        responses: {
            /** @description 선택 근거가 기록된다 (FE-055) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceConflict"];
                };
            };
        };
    };
    startGeneration: {
        parameters: {
            query?: never;
            header: {
                /** @description 같은 설정으로 재요청하면 같은 키를 보낸다. 검토서 §3.4 */
                "Idempotency-Key": string;
            };
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description 작업이 만들어졌다 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description 같은 키로 이미 진행 중. 새 작업을 만들지 않고 그 작업으로 보낸다 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["jobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 폴링 대상 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["jobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 취소 요청됨 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description 이미 끝난 작업 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDecks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 최신순 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DeckRevisionSummary"][];
                    };
                };
            };
        };
    };
    getDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 슬라이드별 핵심 메시지, 출처, 경고를 포함한다 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckRevision"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getDeckPreviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 슬라이드 순서대로 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SlidePreview"][];
                    };
                };
            };
        };
    };
    createDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifactId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 발급됨 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        download_url: string;
                        /** Format: date-time */
                        expires_at: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
